services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    networks:
      - registry_network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    ports:
      - "5080:80"
    environment:
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - registry_network

networks:
  registry_network:
    driver: bridge
