services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    ports:
      - "53:53/udp"
    volumes:
      - ./config/hostsfile:/etc/coredns/hostsfile
      - ./config/Corefile:/Corefile
    restart: unless-stopped
