services:
  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    restart: always
    ports:
      - "2017:2017"
      - "20170-20172:20170-20172"
    environment:
      - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
    volumes:
      - ./etc/v2raya:/etc/v2raya
