global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9200"] # 替换为你的实际 IP 或容器名
  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:9300"]
