services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver overlay2
    restart: always # 可选，根据需要决定是否自动重启
  jenkins-blueocean:
    build:
      context: . # 指定构建上下文，通常是包含 Dockerfile 的目录
      dockerfile: Dockerfile # 如果 Dockerfile 文件名不为 Dockerfile，可以显式指定
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8070:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:
    external: false

volumes:
  jenkins-docker-certs:
  jenkins-data:
