services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    volumes:
      - ./etc/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
