services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: always
    volumes:
      - ./base/pref.toml:/base/pref.toml
    ports:
      - 25500:25500
  # subweb:
  #   build: ./sub-web
  #   container_name: subweb
  #   restart: always
  #   ports:
  #     - "${SUBWEB_PORT}:80"
  # subweb:
  #   image: stilleshan/sub:latest
  #   container_name: subweb
  #   restart: always
  #   volumes:
  #     - ./conf:/usr/share/nginx/html/conf
  #   ports:
  #     - "${SUBWEB_PORT}:80"
  # myurls:
  #   image: "careywong/myurls:latest"
  #   container_name: myurls
  #   restart: always
  #   ports:
  #     - "${MYURLS_PORT}:8080"
  #   volumes:
  #     - ./data/myurls/logs:/app/logs
  #   depends_on:
  #     - myurls-redis
  #   entrypoint: ["/app/myurls", "-domain", "${MYURLS_DOMAIN}", "-conn", myurls-redis:6379]
  # myurls-redis:
  #   image: "redis:7"
  #   container_name: myurls-redis
  #   restart: always
  #   volumes:
  #     - ./data/redis:/data
  #   expose:
  #     - "6379"
