services:
  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 3000 db.json
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data/
      # - ./db.json:/data/db.json
    restart: always
