services:
  clash:
    image: dreamacro/clash:latest
    container_name: clash
    restart: unless-stopped
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "17890:7890/tcp"
      - "17890:7890/udp"
      - "19090:9090"

  yacd:
    image: haishanh/yacd:latest
    container_name: yacd
    restart: unless-stopped
    ports:
      - "9099:80"
    depends_on:
      - clash
